[package]
name = "rusp"
version = "0.1.0"
authors = ["infcode <Wu_QiFei@sjtu.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
